name: Example workflow using Snyk fix
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1
      - name: create PR if some changed file
        if: steps.verify_changed_files.outputs.files_changed == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        #run: |
        #  echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        #  echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
