name: Example workflow using Snyk fix
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with: 
          command: fix
      - name: check uncommited changes
        uses: mskri/check-uncommitted-changes-action@v1.0.1
      - name: Print uncommitted changes
        if: steps.check-changes.outputs.changes != ''
        uses: peter-evans/create-pull-request@v3
      - name: get PR info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
